# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movie3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'ObjectMapper'
pod 'AlamofireImage'

  # Pods for movie3

end
